project:
  type: website
  output-dir: docs

website:
  title: "Batman"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/fahimshafeek
      - icon: twitter
        href: https://twitter.com/
      - icon: instagram
        href: https://instagram.com/gameo__/
format:
  html:
    theme: yeti
    css: styles.css



